repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-mod-tidy
      - id: go-vet
      - id: go-fmt
      - id: go-critic
        args: [ -enableAll ]
      - id: golangci-lint
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-cyclo
        args: [-over=15]