version: "3"
services:
  serviceName-postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: togo-write-postgres
    volumes:
      - togo-write-data:/var/lib/postgresql/data
    expose:
      - 5433
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

volumes:
  togo-write-data:
